name: Generate Snake Animation

on:
  schedule:
    # Run every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake animation
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          # GitHub user name
          github_user_name: ${{ github.repository_owner }}
          # Output path
          outputs: dist/snake.svg

      # Step 3: Push the animation to the output branch
      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
